/* tslint:disable */
/* eslint-disable */
/**
 * Invoke AI
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BodyAppendInvocation,
  HTTPValidationError,
  InvocationGraph,
} from '../models';
import {
    BodyAppendInvocationFromJSON,
    BodyAppendInvocationToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    InvocationGraphFromJSON,
    InvocationGraphToJSON,
} from '../models';

export interface AppendInvocationRequest {
    sessionId: string;
    bodyAppendInvocation: BodyAppendInvocation;
}

export interface CreateSessionRequest {
    invocationGraph?: InvocationGraph;
}

export interface GetSessionRequest {
    sessionId: string;
}

export interface InvokeSessionRequest {
    sessionId: string;
    all?: boolean;
}

export interface ListSessionsRequest {
    page?: number;
    perPage?: number;
}

/**
 * 
 */
export class SessionsApi extends runtime.BaseAPI {

    /**
     * Append Invocation
     */
    async appendInvocationRaw(requestParameters: AppendInvocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters.sessionId === null || requestParameters.sessionId === undefined) {
            throw new runtime.RequiredError('sessionId','Required parameter requestParameters.sessionId was null or undefined when calling appendInvocation.');
        }

        if (requestParameters.bodyAppendInvocation === null || requestParameters.bodyAppendInvocation === undefined) {
            throw new runtime.RequiredError('bodyAppendInvocation','Required parameter requestParameters.bodyAppendInvocation was null or undefined when calling appendInvocation.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/sessions/{session_id}/invocations`.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters.sessionId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BodyAppendInvocationToJSON(requestParameters.bodyAppendInvocation),
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * Append Invocation
     */
    async appendInvocation(requestParameters: AppendInvocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.appendInvocationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a new sessions, optionally initializing it with an invocation graph
     * Create Session
     */
    async createSessionRaw(requestParameters: CreateSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/sessions/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InvocationGraphToJSON(requestParameters.invocationGraph),
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * Creates a new sessions, optionally initializing it with an invocation graph
     * Create Session
     */
    async createSession(requestParameters: CreateSessionRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.createSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Gets a single session
     * Get Session
     */
    async getSessionRaw(requestParameters: GetSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters.sessionId === null || requestParameters.sessionId === undefined) {
            throw new runtime.RequiredError('sessionId','Required parameter requestParameters.sessionId was null or undefined when calling getSession.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/sessions/{session_id}`.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters.sessionId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * Gets a single session
     * Get Session
     */
    async getSession(requestParameters: GetSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Invokes the session
     * Invoke Session
     */
    async invokeSessionRaw(requestParameters: InvokeSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters.sessionId === null || requestParameters.sessionId === undefined) {
            throw new runtime.RequiredError('sessionId','Required parameter requestParameters.sessionId was null or undefined when calling invokeSession.');
        }

        const queryParameters: any = {};

        if (requestParameters.all !== undefined) {
            queryParameters['all'] = requestParameters.all;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/sessions/{session_id}/invoke`.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters.sessionId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * Invokes the session
     * Invoke Session
     */
    async invokeSession(requestParameters: InvokeSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.invokeSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Gets a paged list of sessions ids
     * List Sessions
     */
    async listSessionsRaw(requestParameters: ListSessionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.perPage !== undefined) {
            queryParameters['per_page'] = requestParameters.perPage;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/sessions/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * Gets a paged list of sessions ids
     * List Sessions
     */
    async listSessions(requestParameters: ListSessionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listSessionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
