/* tslint:disable */
/* eslint-disable */
/**
 * Invoke AI
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Invocation } from './Invocation';
import {
    InvocationFromJSON,
    InvocationFromJSONTyped,
    InvocationToJSON,
} from './Invocation';
import type { InvocationFieldLink } from './InvocationFieldLink';
import {
    InvocationFieldLinkFromJSON,
    InvocationFieldLinkFromJSONTyped,
    InvocationFieldLinkToJSON,
} from './InvocationFieldLink';

/**
 * 
 * @export
 * @interface BodyAppendInvocationApiV1SessionsSessionIdInvocationsPost
 */
export interface BodyAppendInvocationApiV1SessionsSessionIdInvocationsPost {
    /**
     * 
     * @type {Invocation}
     * @memberof BodyAppendInvocationApiV1SessionsSessionIdInvocationsPost
     */
    invocation: Invocation;
    /**
     * Links from previous invocations to the new invocation
     * @type {Array<InvocationFieldLink>}
     * @memberof BodyAppendInvocationApiV1SessionsSessionIdInvocationsPost
     */
    links?: Array<InvocationFieldLink>;
}

/**
 * Check if a given object implements the BodyAppendInvocationApiV1SessionsSessionIdInvocationsPost interface.
 */
export function instanceOfBodyAppendInvocationApiV1SessionsSessionIdInvocationsPost(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "invocation" in value;

    return isInstance;
}

export function BodyAppendInvocationApiV1SessionsSessionIdInvocationsPostFromJSON(json: any): BodyAppendInvocationApiV1SessionsSessionIdInvocationsPost {
    return BodyAppendInvocationApiV1SessionsSessionIdInvocationsPostFromJSONTyped(json, false);
}

export function BodyAppendInvocationApiV1SessionsSessionIdInvocationsPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyAppendInvocationApiV1SessionsSessionIdInvocationsPost {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'invocation': InvocationFromJSON(json['invocation']),
        'links': !exists(json, 'links') ? undefined : ((json['links'] as Array<any>).map(InvocationFieldLinkFromJSON)),
    };
}

export function BodyAppendInvocationApiV1SessionsSessionIdInvocationsPostToJSON(value?: BodyAppendInvocationApiV1SessionsSessionIdInvocationsPost | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'invocation': InvocationToJSON(value.invocation),
        'links': value.links === undefined ? undefined : ((value.links as Array<any>).map(InvocationFieldLinkToJSON)),
    };
}

