/* tslint:disable */
/* eslint-disable */
/**
 * Invoke AI
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The node field linked from
 * @export
 * @interface FromNode
 */
export interface FromNode {
    /**
     * The id of the node for this link
     * @type {string}
     * @memberof FromNode
     */
    id: string;
    /**
     * The name of the field for this link
     * @type {string}
     * @memberof FromNode
     */
    field: string;
}

/**
 * Check if a given object implements the FromNode interface.
 */
export function instanceOfFromNode(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "field" in value;

    return isInstance;
}

export function FromNodeFromJSON(json: any): FromNode {
    return FromNodeFromJSONTyped(json, false);
}

export function FromNodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FromNode {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'field': json['field'],
    };
}

export function FromNodeToJSON(value?: FromNode | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'field': value.field,
    };
}

