/* tslint:disable */
/* eslint-disable */
/**
 * Invoke AI
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FromNodeId
 */
export interface FromNodeId {
}

/**
 * Check if a given object implements the FromNodeId interface.
 */
export function instanceOfFromNodeId(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FromNodeIdFromJSON(json: any): FromNodeId {
    return FromNodeIdFromJSONTyped(json, false);
}

export function FromNodeIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): FromNodeId {
    return json;
}

export function FromNodeIdToJSON(value?: FromNodeId | null): any {
    return value;
}

