/* tslint:disable */
/* eslint-disable */
/**
 * Invoke AI
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * And this one is an image.
 * @export
 * @interface ImageInput1
 */
export interface ImageInput1 {
    /**
     * The relative path to the image
     * @type {string}
     * @memberof ImageInput1
     */
    uri?: string;
}

/**
 * Check if a given object implements the ImageInput1 interface.
 */
export function instanceOfImageInput1(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ImageInput1FromJSON(json: any): ImageInput1 {
    return ImageInput1FromJSONTyped(json, false);
}

export function ImageInput1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageInput1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uri': !exists(json, 'uri') ? undefined : json['uri'],
    };
}

export function ImageInput1ToJSON(value?: ImageInput1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uri': value.uri,
    };
}

