/* tslint:disable */
/* eslint-disable */
/**
 * Invoke AI
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 * @export
 */
export const ImageType = {
    Results: 'results',
    Intermediates: 'intermediates'
} as const;
export type ImageType = typeof ImageType[keyof typeof ImageType];


export function ImageTypeFromJSON(json: any): ImageType {
    return ImageTypeFromJSONTyped(json, false);
}

export function ImageTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageType {
    return json as ImageType;
}

export function ImageTypeToJSON(value?: ImageType | null): any {
    return value as any;
}

