/* tslint:disable */
/* eslint-disable */
/**
 * Invoke AI
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The output image
 * @export
 * @interface Image2
 */
export interface Image2 {
    /**
     * The relative path to the image
     * @type {string}
     * @memberof Image2
     */
    uri?: string;
}

/**
 * Check if a given object implements the Image2 interface.
 */
export function instanceOfImage2(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function Image2FromJSON(json: any): Image2 {
    return Image2FromJSONTyped(json, false);
}

export function Image2FromJSONTyped(json: any, ignoreDiscriminator: boolean): Image2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uri': !exists(json, 'uri') ? undefined : json['uri'],
    };
}

export function Image2ToJSON(value?: Image2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uri': value.uri,
    };
}

