/* tslint:disable */
/* eslint-disable */
/**
 * Invoke AI
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Image } from './Image';
import {
    ImageFromJSON,
    ImageFromJSONTyped,
    ImageToJSON,
} from './Image';

/**
 * Generates an image using img2img.
 * @export
 * @interface ImageToImageInvocation
 */
export interface ImageToImageInvocation {
    [key: string]: any | any;
    /**
     * The id of this node. Must be unique among all nodes.
     * @type {string}
     * @memberof ImageToImageInvocation
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ImageToImageInvocation
     */
    type?: ImageToImageInvocationTypeEnum;
    /**
     * The prompt to generate an image from
     * @type {string}
     * @memberof ImageToImageInvocation
     */
    prompt?: string;
    /**
     * The seed to use (0 for a random seed)
     * @type {number}
     * @memberof ImageToImageInvocation
     */
    seed?: number;
    /**
     * The number of steps to use to generate the image
     * @type {number}
     * @memberof ImageToImageInvocation
     */
    steps?: number;
    /**
     * The width of the resulting image
     * @type {number}
     * @memberof ImageToImageInvocation
     */
    width?: number;
    /**
     * The height of the resulting image
     * @type {number}
     * @memberof ImageToImageInvocation
     */
    height?: number;
    /**
     * The Classifier-Free Guidance, higher values may result in a result closer to the prompt
     * @type {number}
     * @memberof ImageToImageInvocation
     */
    cfgScale?: number;
    /**
     * The sampler to use
     * @type {string}
     * @memberof ImageToImageInvocation
     */
    samplerName?: ImageToImageInvocationSamplerNameEnum;
    /**
     * Whether or not to generate an image that can tile without seams
     * @type {boolean}
     * @memberof ImageToImageInvocation
     */
    seamless?: boolean;
    /**
     * The model to use (currently ignored)
     * @type {string}
     * @memberof ImageToImageInvocation
     */
    model?: string;
    /**
     * Whether or not to produce progress images during generation
     * @type {boolean}
     * @memberof ImageToImageInvocation
     */
    progressImages?: boolean;
    /**
     * 
     * @type {Image}
     * @memberof ImageToImageInvocation
     */
    image?: Image;
    /**
     * The strength of the original image
     * @type {number}
     * @memberof ImageToImageInvocation
     */
    strength?: number;
    /**
     * Whether or not the result should be fit to the aspect ratio of the input image
     * @type {boolean}
     * @memberof ImageToImageInvocation
     */
    fit?: boolean;
}


/**
 * @export
 */
export const ImageToImageInvocationTypeEnum = {
    Img2img: 'img2img'
} as const;
export type ImageToImageInvocationTypeEnum = typeof ImageToImageInvocationTypeEnum[keyof typeof ImageToImageInvocationTypeEnum];

/**
 * @export
 */
export const ImageToImageInvocationSamplerNameEnum = {
    Ddim: 'ddim',
    Plms: 'plms',
    KLms: 'k_lms',
    KDpm2: 'k_dpm_2',
    KDpm2A: 'k_dpm_2_a',
    KEuler: 'k_euler',
    KEulerA: 'k_euler_a',
    KHeun: 'k_heun'
} as const;
export type ImageToImageInvocationSamplerNameEnum = typeof ImageToImageInvocationSamplerNameEnum[keyof typeof ImageToImageInvocationSamplerNameEnum];


/**
 * Check if a given object implements the ImageToImageInvocation interface.
 */
export function instanceOfImageToImageInvocation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function ImageToImageInvocationFromJSON(json: any): ImageToImageInvocation {
    return ImageToImageInvocationFromJSONTyped(json, false);
}

export function ImageToImageInvocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageToImageInvocation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'prompt': !exists(json, 'prompt') ? undefined : json['prompt'],
        'seed': !exists(json, 'seed') ? undefined : json['seed'],
        'steps': !exists(json, 'steps') ? undefined : json['steps'],
        'width': !exists(json, 'width') ? undefined : json['width'],
        'height': !exists(json, 'height') ? undefined : json['height'],
        'cfgScale': !exists(json, 'cfg_scale') ? undefined : json['cfg_scale'],
        'samplerName': !exists(json, 'sampler_name') ? undefined : json['sampler_name'],
        'seamless': !exists(json, 'seamless') ? undefined : json['seamless'],
        'model': !exists(json, 'model') ? undefined : json['model'],
        'progressImages': !exists(json, 'progress_images') ? undefined : json['progress_images'],
        'image': !exists(json, 'image') ? undefined : ImageFromJSON(json['image']),
        'strength': !exists(json, 'strength') ? undefined : json['strength'],
        'fit': !exists(json, 'fit') ? undefined : json['fit'],
    };
}

export function ImageToImageInvocationToJSON(value?: ImageToImageInvocation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
            ...value,
        'id': value.id,
        'type': value.type,
        'prompt': value.prompt,
        'seed': value.seed,
        'steps': value.steps,
        'width': value.width,
        'height': value.height,
        'cfg_scale': value.cfgScale,
        'sampler_name': value.samplerName,
        'seamless': value.seamless,
        'model': value.model,
        'progress_images': value.progressImages,
        'image': ImageToJSON(value.image),
        'strength': value.strength,
        'fit': value.fit,
    };
}

