/* tslint:disable */
/* eslint-disable */
/**
 * Invoke AI
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * An image output
 * @export
 * @interface ImageOutput
 */
export interface ImageOutput {
    /**
     * The relative path to the image
     * @type {string}
     * @memberof ImageOutput
     */
    uri?: string;
}

/**
 * Check if a given object implements the ImageOutput interface.
 */
export function instanceOfImageOutput(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ImageOutputFromJSON(json: any): ImageOutput {
    return ImageOutputFromJSONTyped(json, false);
}

export function ImageOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageOutput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uri': !exists(json, 'uri') ? undefined : json['uri'],
    };
}

export function ImageOutputToJSON(value?: ImageOutput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uri': value.uri,
    };
}

