/* tslint:disable */
/* eslint-disable */
/**
 * Invoke AI
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * An image field used for passing image objects between invocations
 * @export
 * @interface ImageField
 */
export interface ImageField {
    /**
     * The relative path to the image
     * @type {string}
     * @memberof ImageField
     */
    uri?: string;
}

/**
 * Check if a given object implements the ImageField interface.
 */
export function instanceOfImageField(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ImageFieldFromJSON(json: any): ImageField {
    return ImageFieldFromJSONTyped(json, false);
}

export function ImageFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageField {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uri': !exists(json, 'uri') ? undefined : json['uri'],
    };
}

export function ImageFieldToJSON(value?: ImageField | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uri': value.uri,
    };
}

