/* tslint:disable */
/* eslint-disable */
/**
 * Invoke AI
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FromNodeId } from './FromNodeId';
import {
    FromNodeIdFromJSON,
    FromNodeIdFromJSONTyped,
    FromNodeIdToJSON,
} from './FromNodeId';

/**
 * 
 * @export
 * @interface InvocationFieldLink
 */
export interface InvocationFieldLink {
    /**
     * 
     * @type {FromNodeId}
     * @memberof InvocationFieldLink
     */
    fromNodeId: FromNodeId;
    /**
     * 
     * @type {string}
     * @memberof InvocationFieldLink
     */
    fromField: string;
    /**
     * 
     * @type {string}
     * @memberof InvocationFieldLink
     */
    toField: string;
}

/**
 * Check if a given object implements the InvocationFieldLink interface.
 */
export function instanceOfInvocationFieldLink(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "fromNodeId" in value;
    isInstance = isInstance && "fromField" in value;
    isInstance = isInstance && "toField" in value;

    return isInstance;
}

export function InvocationFieldLinkFromJSON(json: any): InvocationFieldLink {
    return InvocationFieldLinkFromJSONTyped(json, false);
}

export function InvocationFieldLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvocationFieldLink {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fromNodeId': FromNodeIdFromJSON(json['from_node_id']),
        'fromField': json['from_field'],
        'toField': json['to_field'],
    };
}

export function InvocationFieldLinkToJSON(value?: InvocationFieldLink | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'from_node_id': FromNodeIdToJSON(value.fromNodeId),
        'from_field': value.fromField,
        'to_field': value.toField,
    };
}

