/* tslint:disable */
/* eslint-disable */
/**
 * Invoke AI
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Image1 } from './Image1';
import {
    Image1FromJSON,
    Image1FromJSONTyped,
    Image1ToJSON,
} from './Image1';

/**
 * Displays a provided image, and passes it forward in the pipeline.
 * @export
 * @interface ShowImageInvocation
 */
export interface ShowImageInvocation {
    [key: string]: any | any;
    /**
     * The id of this node. Must be unique among all nodes.
     * @type {string}
     * @memberof ShowImageInvocation
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ShowImageInvocation
     */
    type?: ShowImageInvocationTypeEnum;
    /**
     * 
     * @type {Image1}
     * @memberof ShowImageInvocation
     */
    image?: Image1;
}


/**
 * @export
 */
export const ShowImageInvocationTypeEnum = {
    ShowImage: 'show_image'
} as const;
export type ShowImageInvocationTypeEnum = typeof ShowImageInvocationTypeEnum[keyof typeof ShowImageInvocationTypeEnum];


/**
 * Check if a given object implements the ShowImageInvocation interface.
 */
export function instanceOfShowImageInvocation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function ShowImageInvocationFromJSON(json: any): ShowImageInvocation {
    return ShowImageInvocationFromJSONTyped(json, false);
}

export function ShowImageInvocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShowImageInvocation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'image': !exists(json, 'image') ? undefined : Image1FromJSON(json['image']),
    };
}

export function ShowImageInvocationToJSON(value?: ShowImageInvocation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
            ...value,
        'id': value.id,
        'type': value.type,
        'image': Image1ToJSON(value.image),
    };
}

