/* tslint:disable */
/* eslint-disable */
/**
 * Invoke AI
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Provides a plain text prompt.
 * @export
 * @interface SimplePromptInvocation
 */
export interface SimplePromptInvocation {
    [key: string]: any | any;
    /**
     * The id of this node. Must be unique among all nodes.
     * @type {string}
     * @memberof SimplePromptInvocation
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SimplePromptInvocation
     */
    type?: SimplePromptInvocationTypeEnum;
    /**
     * The prompt
     * @type {string}
     * @memberof SimplePromptInvocation
     */
    prompt?: string;
}


/**
 * @export
 */
export const SimplePromptInvocationTypeEnum = {
    SimplePrompt: 'simple_prompt'
} as const;
export type SimplePromptInvocationTypeEnum = typeof SimplePromptInvocationTypeEnum[keyof typeof SimplePromptInvocationTypeEnum];


/**
 * Check if a given object implements the SimplePromptInvocation interface.
 */
export function instanceOfSimplePromptInvocation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function SimplePromptInvocationFromJSON(json: any): SimplePromptInvocation {
    return SimplePromptInvocationFromJSONTyped(json, false);
}

export function SimplePromptInvocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimplePromptInvocation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'prompt': !exists(json, 'prompt') ? undefined : json['prompt'],
    };
}

export function SimplePromptInvocationToJSON(value?: SimplePromptInvocation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
            ...value,
        'id': value.id,
        'type': value.type,
        'prompt': value.prompt,
    };
}

