/* tslint:disable */
/* eslint-disable */
/**
 * Invoke AI
 * An API for invoking AI image operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Output used by SimplePromptInvocation
 * @export
 * @interface SimplePromptInvocationOutput
 */
export interface SimplePromptInvocationOutput {
    /**
     * 
     * @type {string}
     * @memberof SimplePromptInvocationOutput
     */
    type?: SimplePromptInvocationOutputTypeEnum;
    /**
     * The prompt to use
     * @type {string}
     * @memberof SimplePromptInvocationOutput
     */
    prompt: string;
}


/**
 * @export
 */
export const SimplePromptInvocationOutputTypeEnum = {
    SimplePromptOutput: 'simple_prompt_output'
} as const;
export type SimplePromptInvocationOutputTypeEnum = typeof SimplePromptInvocationOutputTypeEnum[keyof typeof SimplePromptInvocationOutputTypeEnum];


/**
 * Check if a given object implements the SimplePromptInvocationOutput interface.
 */
export function instanceOfSimplePromptInvocationOutput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "prompt" in value;

    return isInstance;
}

export function SimplePromptInvocationOutputFromJSON(json: any): SimplePromptInvocationOutput {
    return SimplePromptInvocationOutputFromJSONTyped(json, false);
}

export function SimplePromptInvocationOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimplePromptInvocationOutput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'prompt': json['prompt'],
    };
}

export function SimplePromptInvocationOutputToJSON(value?: SimplePromptInvocationOutput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'prompt': value.prompt,
    };
}

