import {
  HEIGHTS,
  NUMPY_RAND_MAX,
  NUMPY_RAND_MIN,
  SAMPLERS,
  WIDTHS,
} from '../../../app/constants';
import { Module } from '../types';
import { v4 as uuidv4 } from 'uuid';

const makeGenerateModule = (): Module => {
  return {
    moduleId: uuidv4(),
    moduleType: 'generate',
    moduleLabel: 'Generate',
    parameters: {
      prompt: {
        id: 'prompt',
        label: 'Prompt',
        uiType: 'text',
        dataType: 'string',
        value: '',
        connectable: ['target'],
      },
      input_image: {
        id: 'input_image',
        label: 'Initial image',
        uiType: 'image',
        dataType: 'image',
        value: '',
        connectable: ['target'],
        optional: true,
      },
      strength: {
        id: 'strength',
        label: 'Initial image strength',
        uiType: 'slider',
        dataType: 'number',
        min: 0,
        max: 1,
        value: 0.75,
        step: 0.01,
        dependsOn: 'input_image',
        withNumberInput: true,
      },
      sampler_name: {
        id: 'sampler_name',
        label: 'Sampler',
        uiType: 'select',
        dataType: 'string',
        value: 'k_lms',
        options: SAMPLERS,
      },
      seed: {
        id: 'seed',
        label: 'Seed',
        uiType: 'numberInput',
        dataType: 'number',
        min: NUMPY_RAND_MIN,
        max: NUMPY_RAND_MAX,
        step: 1,
        value: 12345,
        withRandomizeIconButton: true,
      },
      steps: {
        id: 'steps',
        label: 'Steps',
        uiType: 'slider',
        dataType: 'number',
        value: 32,
        min: 1,
        max: 200,
        step: 1,
        withNumberInput: true,
        numberInputMax: Infinity,
      },
      cfg_scale: {
        id: 'cfg_scale',
        label: 'CFG Scale',
        uiType: 'slider',
        dataType: 'number',
        value: 7.5,
        min: 0,
        max: 10,
        step: 0.1,
        exclusiveMinimum: true,
        withNumberInput: true,
      },
      width: {
        id: 'width',
        label: 'Width',
        uiType: 'select',
        dataType: 'number',
        value: 512,
        options: WIDTHS,
      },
      height: {
        id: 'height',
        label: 'Height',
        uiType: 'select',
        dataType: 'number',
        value: 512,
        options: HEIGHTS,
      },
      seamless: {
        id: 'seamless',
        label: 'Seamless',
        uiType: 'toggle',
        dataType: 'boolean',
        value: false,
      },
      output_image: {
        id: 'output_image',
        label: 'Output image',
        uiType: 'image',
        dataType: 'image',
        value: '',
        connectable: ['source'],
      },
    },
  };
};

export default makeGenerateModule;
